package org.JukeBugs.vo;

import java.io.Serializable;

/**
 * 친구 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Friend implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private String userId;

	/** 사용자. */
	private String requestId;
		
	private String userNick;
		
	private boolean followback;
		
	private int compatibility;

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public String getUserNick() {
		return userNick;
	}

	public void setUserNick(String userNick) {
		this.userNick = userNick;
	}

	public boolean isFollowback() {
		return followback;
	}

	public void setFollowback(boolean followback) {
		this.followback = followback;
	}

	public int getCompatibility() {
		return compatibility;
	}

	public void setCompatibility(int compatibility) {
		this.compatibility = compatibility;
	}

	@Override
	public String toString() {
		return "Friend [userId=" + userId + ", requestId=" + requestId + ", userNick=" + userNick + ", followback="
				+ followback + ", compatibility=" + compatibility + "]";
	} 
	
}
