package org.JukeBugs.vo;

import java.io.Serializable;

/**
 * 신고 가수 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportArtist implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private int reportid;

	private String artistid;

	public int getReportid() {
		return reportid;
	}

	public void setReportid(int reportid) {
		this.reportid = reportid;
	}

	public String getArtistid() {
		return artistid;
	}

	public void setArtistid(String artistid) {
		this.artistid = artistid;
	}

	@Override
	public String toString() {
		return "ReportArtist [reportid=" + reportid + ", artistid=" + artistid + "]";
	}


}
