package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 가수 앨범 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ArtistAlbum implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 앨범의 아이디. */
	private String albumid;

	/** 앨범 출시일자. */
	private String albumrelease;

	/** 앨범 명. */
	private String albumtitle;

	/** 앨범 상세 설명. */
	private String albumdiscription;

	/** 앨범 이미지 URL. */
	private String albumimgurl;

	private int ranking;
	private String artistName;

	/**
	 * 생성자.
	 */
	public ArtistAlbum() {
	}

	public ArtistAlbum(String albumid, String albumrelease, String albumtitle, String albumdiscription,
			String albumimgurl) {
		this.albumid = albumid;
		this.albumrelease = albumrelease;
		this.albumtitle = albumtitle;
		this.albumdiscription = albumdiscription;
		this.albumimgurl = albumimgurl;
	}

	/**
	 * 앨범의 아이디을 설정합니다..
	 * 
	 * @param albumid
	 *            앨범의 아이디
	 */
	public void setAlbumid(String albumid) {
		this.albumid = albumid;
	}

	/**
	 * 앨범의 아이디을 가져옵니다..
	 * 
	 * @return 앨범의 아이디
	 */
	public String getAlbumid() {
		return this.albumid;
	}

	public String getAlbumrelease() {
		return albumrelease;
	}

	public void setAlbumrelease(String albumrelease) {
		this.albumrelease = albumrelease;
	}

	/**
	 * 앨범 명을 설정합니다..
	 * 
	 * @param albumtitle
	 *            앨범 명
	 */
	public void setAlbumtitle(String albumtitle) {
		this.albumtitle = albumtitle;
	}

	/**
	 * 앨범 명을 가져옵니다..
	 * 
	 * @return 앨범 명
	 */
	public String getAlbumtitle() {
		return this.albumtitle;
	}

	/**
	 * 앨범 상세 설명을 설정합니다..
	 * 
	 * @param albumdiscription
	 *            앨범 상세 설명
	 */
	public void setAlbumdiscription(String albumdiscription) {
		this.albumdiscription = albumdiscription;
	}

	/**
	 * 앨범 상세 설명을 가져옵니다..
	 * 
	 * @return 앨범 상세 설명
	 */
	public String getAlbumdiscription() {
		return this.albumdiscription;
	}

	/**
	 * 앨범 이미지 URL을 설정합니다..
	 * 
	 * @param albumimgurl
	 *            앨범 이미지 URL
	 */
	public void setAlbumimgurl(String albumimgurl) {
		this.albumimgurl = albumimgurl;
	}

	/**
	 * 앨범 이미지 URL을 가져옵니다..
	 * 
	 * @return 앨범 이미지 URL
	 */
	public String getAlbumimgurl() {
		return this.albumimgurl;
	}

	public int getRanking() {
		return ranking;
	}

	public void setRanking(int ranking) {
		this.ranking = ranking;
	}

	public String getArtistName() {
		return artistName;
	}

	public void setArtistName(String artistName) {
		this.artistName = artistName;
	}

	@Override
	public String toString() {
		return "ArtistAlbum [albumid=" + albumid + ", albumrelease=" + albumrelease + ", albumtitle=" + albumtitle
				+ ", albumdiscription=" + albumdiscription + ", albumimgurl=" + albumimgurl + ", ranking=" + ranking
				+ "]";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((albumid == null) ? 0 : albumid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ArtistAlbum other = (ArtistAlbum) obj;
		if (albumid == null) {
			if (other.albumid != null) {
				return false;
			}
		} else if (!albumid.equals(other.albumid)) {
			return false;
		}
		return true;
	}

}
