package org.JukeBugs.vo;

import java.io.Serializable;

/**
 * 즐겨찾기 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Like implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private String userId;

	/** 노래. */
	private Song songId;

	/**
	 * 생성자.
	 */
	public Like() {
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Song getSongId() {
		return songId;
	}

	public void setSongId(Song songId) {
		this.songId = songId;
	}

	@Override
	public String toString() {
		return "Like [userId=" + userId + ", songId=" + songId + "]";
	}


}
