package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 접근기록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Log implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자. */
	private Jbuser jbuser;

	/** 노래. */
	private Song song;

	/** 유저 커스터마이징 앨범. */
	private MakeAlbum makeAlbum;

	/** 접근기록. */
	private String accesslog;

	/** 접근타입. */
	private String accesstype;
	
	private String songtitle;
	
	private String releasedate;
	
	private String albumid;
	
	private String source;
	
	private String artistname;
	
	private String artistid;
	
	private String artistimgurl;
	
	private String albumtitle;
	
	private String albumimgurl;
	
	private String songid;
	
	private String userid;
	
	
	public Log() {
	}
	

	/**
	 * 사용자을 설정합니다..
	 * 
	 * @param jbuser
	 *            사용자
	 */
	public void setJbuser(Jbuser jbuser) {
		this.jbuser = jbuser;
	}

	/**
	 * 사용자을 가져옵니다..
	 * 
	 * @return 사용자
	 */
	public Jbuser getJbuser() {
		return this.jbuser;
	}

	/**
	 * 노래을 설정합니다..
	 * 
	 * @param song
	 *            노래
	 */
	public void setSong(Song song) {
		this.song = song;
	}

	/**
	 * 노래을 가져옵니다..
	 * 
	 * @return 노래
	 */
	public Song getSong() {
		return this.song;
	}

	/**
	 * 유저 커스터마이징 앨범을 설정합니다..
	 * 
	 * @param makeAlbum
	 *            유저 커스터마이징 앨범
	 */
	public void setMakeAlbum(MakeAlbum makeAlbum) {
		this.makeAlbum = makeAlbum;
	}

	/**
	 * 유저 커스터마이징 앨범을 가져옵니다..
	 * 
	 * @return 유저 커스터마이징 앨범
	 */
	public MakeAlbum getMakeAlbum() {
		return this.makeAlbum;
	}

	
	public String getAccesslog() {
		return accesslog;
	}

	public void setAccesslog(String accesslog) {
		this.accesslog = accesslog;
	}

	/**
	 * 접근타입을 설정합니다..
	 * 
	 * @param accesstype
	 *            접근타입
	 */
	public void setAccesstype(String accesstype) {
		this.accesstype = accesstype;
	}

	/**
	 * 접근타입을 가져옵니다..
	 * 
	 * @return 접근타입
	 */
	public String getAccesstype() {
		return this.accesstype;
	}

	public String getSongtitle() {
		return songtitle;
	}

	public void setSongtitle(String songtitle) {
		this.songtitle = songtitle;
	}

	public String getReleasedate() {
		return releasedate;
	}

	public void setReleasedate(String releasedate) {
		this.releasedate = releasedate;
	}

	public String getAlbumid() {
		return albumid;
	}

	public void setAlbumid(String albumid) {
		this.albumid = albumid;
	}

	public String getSource() {
		return source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getArtistname() {
		return artistname;
	}

	public void setArtistname(String artistname) {
		this.artistname = artistname;
	}

	public String getArtistid() {
		return artistid;
	}

	public void setArtistid(String artistid) {
		this.artistid = artistid;
	}

	public String getArtistimgurl() {
		return artistimgurl;
	}

	public void setArtistimgurl(String artistimgurl) {
		this.artistimgurl = artistimgurl;
	}

	public String getAlbumtitle() {
		return albumtitle;
	}

	public void setAlbumtitle(String albumtitle) {
		this.albumtitle = albumtitle;
	}

	public String getAlbumimgurl() {
		return albumimgurl;
	}

	public void setAlbumimgurl(String albumimgurl) {
		this.albumimgurl = albumimgurl;
	}
	
	

	public String getSongid() {
		return songid;
	}


	public void setSongid(String songid) {
		this.songid = songid;
	}


	public String getUserid() {
		return userid;
	}


	public void setUserid(String userid) {
		this.userid = userid;
	}


	@Override
	public String toString() {
		return "Log [jbuser=" + jbuser + ", song=" + song + ", makeAlbum=" + makeAlbum + ", accesslog=" + accesslog
				+ ", accesstype=" + accesstype + ", songtitle=" + songtitle + ", releasedate=" + releasedate
				+ ", albumid=" + albumid + ", source=" + source + ", artistname=" + artistname + ", artistid="
				+ artistid + ", artistimgurl=" + artistimgurl + ", albumtitle=" + albumtitle + ", albumimgurl="
				+ albumimgurl + ", songid=" + songid + ", userid=" + userid + "]";
	}


}
