package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;

/**
 * 유저 커스터마이징 앨범 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MakeAlbum implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 앨범 식별자. */
	private String makealbumid;

	/** 앨범 이름. */
	private String makealbumname;

	/** 앨범 접근 수. */
	private int makealbumaccess;

	/** 사용자. */
	private String userid;

	/** 노래. */
	private Song song;

	
	private int count;
	
	private String originalfile; //파일 원래이름
	
	private String savedfile; //겹칠 경우를 대비해서 파일이름
	
	private MultipartFile file;


	/**
	 * 앨범 식별자을 설정합니다..
	 * 
	 * @param makealbumid
	 *            앨범 식별자
	 */
	public void setMakealbumid(String makealbumid) {
		this.makealbumid = makealbumid;
	}

	/**
	 * 앨범 식별자을 가져옵니다..
	 * 
	 * @return 앨범 식별자
	 */
	public String getMakealbumid() {
		return this.makealbumid;
	}

	/**
	 * 앨범 이름을 설정합니다..
	 * 
	 * @param makealbumname
	 *            앨범 이름
	 */
	public void setMakealbumname(String makealbumname) {
		this.makealbumname = makealbumname;
	}

	/**
	 * 앨범 이름을 가져옵니다..
	 * 
	 * @return 앨범 이름
	 */
	public String getMakealbumname() {
		return this.makealbumname;
	}


	public int getMakealbumaccess() {
		return makealbumaccess;
	}

	public void setMakealbumaccess(int makealbumaccess) {
		this.makealbumaccess = makealbumaccess;
	}

	public String getUserid() {
		return userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * 노래을 설정합니다..
	 * 
	 * @param song
	 *            노래
	 */
	public void setSong(Song song) {
		this.song = song;
	}

	/**
	 * 노래을 가져옵니다..
	 * 
	 * @return 노래
	 */
	public Song getSong() {
		return this.song;
	}

	

	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}
	

	public String getOriginalfile() {
		return originalfile;
	}

	public void setOriginalfile(String originalfile) {
		this.originalfile = originalfile;
	}

	public String getSavedfile() {
		return savedfile;
	}

	public void setSavedfile(String savedfile) {
		this.savedfile = savedfile;
	}
	
	
	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}


	@Override
	public String toString() {
		return "MakeAlbum [makealbumid=" + makealbumid + ", makealbumname=" + makealbumname + ", makealbumaccess="
				+ makealbumaccess + ", userid=" + userid + ", song=" + song + ", count=" + count + ", originalfile="
				+ originalfile + ", savedfile=" + savedfile + ", file=" + file + "]";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((makealbumid == null) ? 0 : makealbumid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		MakeAlbum other = (MakeAlbum) obj;
		if (makealbumid == null) {
			if (other.makealbumid != null) {
				return false;
			}
		} else if (!makealbumid.equals(other.makealbumid)) {
			return false;
		}
		return true;
	}

}
