package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 쪽지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Message implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 메세지 아이디. */
	private String messageid;

	/** 메세지 내용. */
	private String message;

	/** 송신날짜. */
	private String senddate;

	/** 사용자. */
	private String sendidjbuser;

	/** 사용자. */
	private String requestIdjbuser;

	

	public String getMessageid() {
		return messageid;
	}

	public void setMessageid(String messageid) {
		this.messageid = messageid;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getSenddate() {
		return senddate;
	}

	public void setSenddate(String senddate) {
		this.senddate = senddate;
	}

	public String getSendidjbuser() {
		return sendidjbuser;
	}

	public void setSendidjbuser(String sendidjbuser) {
		this.sendidjbuser = sendidjbuser;
	}

	public String getRequestIdjbuser() {
		return requestIdjbuser;
	}

	public void setRequestIdjbuser(String requestIdjbuser) {
		this.requestIdjbuser = requestIdjbuser;
	}
	

	@Override
	public String toString() {
		return "Message [messageid=" + messageid + ", message=" + message + ", senddate=" + senddate + ", sendidjbuser="
				+ sendidjbuser + ", requestIdjbuser=" + requestIdjbuser + "]";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((messageid == null) ? 0 : messageid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Message other = (Message) obj;
		if (messageid == null) {
			if (other.messageid != null) {
				return false;
			}
		} else if (!messageid.equals(other.messageid)) {
			return false;
		}
		return true;
	}

}
