package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 뮤직피드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Musicfeed implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 등록날짜. 유저아이디+등록시간(나노초까지) */
	private String musicfeedid;

	/** 작성날짜. */
	private String writedate;

	/** 등록 글. */
	private String writemessage;

	/** 뮤직피드 제목. */
	private String musicfeedtitle;

	/** 사용자. */
	private String writerUser;
	
	


	public String getMusicfeedid() {
		return musicfeedid;
	}

	public void setMusicfeedid(String musicfeedid) {
		this.musicfeedid = musicfeedid;
	}

	public String getWritedate() {
		return writedate;
	}

	public void setWritedate(String writedate) {
		this.writedate = writedate;
	}

	public String getWritemessage() {
		return writemessage;
	}

	public void setWritemessage(String writemessage) {
		this.writemessage = writemessage;
	}

	public String getMusicfeedtitle() {
		return musicfeedtitle;
	}

	public void setMusicfeedtitle(String musicfeedtitle) {
		this.musicfeedtitle = musicfeedtitle;
	}

	public String getWriterUser() {
		return writerUser;
	}

	public void setWriterUser(String writerUser) {
		this.writerUser = writerUser;
	}
	
	@Override
	public String toString() {
		return "Musicfeed [musicfeedid=" + musicfeedid + ", writedate=" + writedate + ", writemessage=" + writemessage
				+ ", musicfeedtitle=" + musicfeedtitle + ", writerUser=" + writerUser + "]";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((musicfeedid == null) ? 0 : musicfeedid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Musicfeed other = (Musicfeed) obj;
		if (musicfeedid == null) {
			if (other.musicfeedid != null) {
				return false;
			}
		} else if (!musicfeedid.equals(other.musicfeedid)) {
			return false;
		}
		return true;
	}

}
