package org.JukeBugs.vo;

import java.io.Serializable;

/**
 * 신고 뮤직 피드 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportMusicfeed implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private int reportid;
	
	private String musicfeedid;

	public int getReportid() {
		return reportid;
	}

	public void setReportid(int reportid) {
		this.reportid = reportid;
	}

	public String getMusicfeedid() {
		return musicfeedid;
	}

	public void setMusicfeedid(String musicfeedid) {
		this.musicfeedid = musicfeedid;
	}

	@Override
	public String toString() {
		return "ReportMusicfeed [reportid=" + reportid + ", musicfeedid=" + musicfeedid + "]";
	}
	
}
