package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import org.springframework.web.multipart.MultipartFile;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Jbuser implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 사용자 아이디. */
	private String userid;

	/** 사용자 비밀번호. */
	private String userpassword;

	/** 사용자 이름. */
	private String username;

	/** 사용자 닉네임. */
	private String usernick;

	/** 사용자 선택 장르 1. */
	private String userlike1;

	/** 사용자 선택 장르 2. */
	private String userlike2;

	/** 사용자 선택 장르 3. */
	private String userlike3;

	/** 비밀번호 찾기 질문. */
	private String userquestion;

	/** 비밀번호 찾기 답. */
	private String useranswer;
	
	private String userprofileimgurl;
	
	private MultipartFile file;

	/** 불량 유저 확인. */
	private String userillegal;
	
	public Jbuser() {
	}

	public Jbuser(String userid, String userpassword, String username, String usernick, String userlike1,
			String userlike2, String userlike3, String userquestion, String useranswer, String userprofileimgurl,
			String userillegal) {
		super();
		this.userid = userid;
		this.userpassword = userpassword;
		this.username = username;
		this.usernick = usernick;
		this.userlike1 = userlike1;
		this.userlike2 = userlike2;
		this.userlike3 = userlike3;
		this.userquestion = userquestion;
		this.useranswer = useranswer;
		this.userprofileimgurl = userprofileimgurl;
		this.userillegal = userillegal;
	}

	/**
	 * 사용자 아이디을 설정합니다..
	 * 
	 * @param userid
	 *            사용자 아이디
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * 사용자 아이디을 가져옵니다..
	 * 
	 * @return 사용자 아이디
	 */
	public String getUserid() {
		return this.userid;
	}

	/**
	 * 사용자 비밀번호을 설정합니다..
	 * 
	 * @param userpassword
	 *            사용자 비밀번호
	 */
	public void setUserpassword(String userpassword) {
		this.userpassword = userpassword;
	}

	/**
	 * 사용자 비밀번호을 가져옵니다..
	 * 
	 * @return 사용자 비밀번호
	 */
	public String getUserpassword() {
		return this.userpassword;
	}

	/**
	 * 사용자 이름을 설정합니다..
	 * 
	 * @param username
	 *            사용자 이름
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * 사용자 이름을 가져옵니다..
	 * 
	 * @return 사용자 이름
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * 사용자 닉네임을 설정합니다..
	 * 
	 * @param usernick
	 *            사용자 닉네임
	 */
	public void setUsernick(String usernick) {
		this.usernick = usernick;
	}

	/**
	 * 사용자 닉네임을 가져옵니다..
	 * 
	 * @return 사용자 닉네임
	 */
	public String getUsernick() {
		return this.usernick;
	}

	/**
	 * 사용자 선택 장르 1을 설정합니다..
	 * 
	 * @param userlike1
	 *            사용자 선택 장르 1
	 */
	public void setUserlike1(String userlike1) {
		this.userlike1 = userlike1;
	}

	/**
	 * 사용자 선택 장르 1을 가져옵니다..
	 * 
	 * @return 사용자 선택 장르 1
	 */
	public String getUserlike1() {
		return this.userlike1;
	}

	/**
	 * 사용자 선택 장르 2을 설정합니다..
	 * 
	 * @param userlike2
	 *            사용자 선택 장르 2
	 */
	public void setUserlike2(String userlike2) {
		this.userlike2 = userlike2;
	}

	/**
	 * 사용자 선택 장르 2을 가져옵니다..
	 * 
	 * @return 사용자 선택 장르 2
	 */
	public String getUserlike2() {
		return this.userlike2;
	}

	/**
	 * 사용자 선택 장르 3을 설정합니다..
	 * 
	 * @param userlike3
	 *            사용자 선택 장르 3
	 */
	public void setUserlike3(String userlike3) {
		this.userlike3 = userlike3;
	}

	/**
	 * 사용자 선택 장르 3을 가져옵니다..
	 * 
	 * @return 사용자 선택 장르 3
	 */
	public String getUserlike3() {
		return this.userlike3;
	}

	/**
	 * 비밀번호 찾기 질문을 설정합니다..
	 * 
	 * @param userquestion
	 *            비밀번호 찾기 질문
	 */
	public void setUserquestion(String userquestion) {
		this.userquestion = userquestion;
	}

	/**
	 * 비밀번호 찾기 질문을 가져옵니다..
	 * 
	 * @return 비밀번호 찾기 질문
	 */
	public String getUserquestion() {
		return this.userquestion;
	}

	/**
	 * 비밀번호 찾기 답을 설정합니다..
	 * 
	 * @param useranswer
	 *            비밀번호 찾기 답
	 */
	public void setUseranswer(String useranswer) {
		this.useranswer = useranswer;
	}

	/**
	 * 비밀번호 찾기 답을 가져옵니다..
	 * 
	 * @return 비밀번호 찾기 답
	 */
	public String getUseranswer() {
		return this.useranswer;
	}
	

	public String getUserprofileimgurl() {
		return userprofileimgurl;
	}

	public void setUserprofileimgurl(String userprofileimgurl) {
		this.userprofileimgurl = userprofileimgurl;
	}

	public MultipartFile getFile() {
		return file;
	}

	public void setFile(MultipartFile file) {
		this.file = file;
	}

	/**
	 * 불량 유저 확인을 설정합니다..
	 * 
	 * @param userillegal
	 *            불량 유저 확인
	 */
	public void setUserillegal(String userillegal) {
		this.userillegal = userillegal;
	}
	

	/**
	 * 불량 유저 확인을 가져옵니다..
	 * 
	 * @return 불량 유저 확인
	 */
	public String getUserillegal() {
		return this.userillegal;
	}
	
	

	@Override
	public String toString() {
		return "Jbuser [userid=" + userid + ", userpassword=" + userpassword + ", username=" + username + ", usernick="
				+ usernick + ", userlike1=" + userlike1 + ", userlike2=" + userlike2 + ", userlike3=" + userlike3
				+ ", userquestion=" + userquestion + ", useranswer=" + useranswer + ", userprofileimgurl="
				+ userprofileimgurl + ", file=" + file + ", userillegal=" + userillegal + "]";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userid == null) ? 0 : userid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Jbuser other = (Jbuser) obj;
		if (userid == null) {
			if (other.userid != null) {
				return false;
			}
		} else if (!userid.equals(other.userid)) {
			return false;
		}
		return true;
	}

}
