package org.JukeBugs.vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 관계 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Relation implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 검색 내용. */
	private String searchitem;

	/** 검색 시간. */
	private String searchdate;

	private String songid;
	
	private String tagvalue;
	
	private String albumid;
	
	private String artistid;
	
	private String userid;
	/**
	 * 생성자.
	 */
	public Relation() {
	}
	public String getSearchitem() {
		return searchitem;
	}
	public void setSearchitem(String searchitem) {
		this.searchitem = searchitem;
	}
	public String getSearchdate() {
		return searchdate;
	}
	public void setSearchdate(String searchdate) {
		this.searchdate = searchdate;
	}
	public String getSongid() {
		return songid;
	}
	public void setSongid(String songid) {
		this.songid = songid;
	}
	public String getTagvalue() {
		return tagvalue;
	}
	public void setTagvalue(String tagvalue) {
		this.tagvalue = tagvalue;
	}
	public String getAlbumid() {
		return albumid;
	}
	public void setAlbumid(String albumid) {
		this.albumid = albumid;
	}
	public String getArtistid() {
		return artistid;
	}
	public void setArtistid(String artistid) {
		this.artistid = artistid;
	}
	public String getUserid() {
		return userid;
	}
	public void setUserid(String userid) {
		this.userid = userid;
	}
	public static long getSerialversionuid() {
		return serialVersionUID;
	}
	@Override
	public String toString() {
		return "Relation [searchitem=" + searchitem + ", searchdate=" + searchdate + ", songid=" + songid
				+ ", tagvalue=" + tagvalue + ", albumid=" + albumid + ", artistid=" + artistid + ", userid=" + userid
				+ "]";
	}
	
}
