package org.JukeBugs.vo;

import java.io.Serializable;

/**
 * 신고 가수 앨범 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportArtistAlbum implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	private int reportid;
	private String albumid;
	
	
	public int getReportid() {
		return reportid;
	}
	public void setReportid(int reportid) {
		this.reportid = reportid;
	}
	public String getAlbumid() {
		return albumid;
	}
	public void setAlbumid(String albumid) {
		this.albumid = albumid;
	}
	@Override
	public String toString() {
		return "ReportArtistAlbum [reportid=" + reportid + ", albumid=" + albumid + "]";
	}
	
}
