package org.JukeBugs.vo;

import java.io.Serializable;

/**
 * 신고 노래 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReportSong implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	private int reportid;
	
	private String songid;

	public int getReportid() {
		return reportid;
	}

	public void setReportid(int reportid) {
		this.reportid = reportid;
	}

	public String getSongid() {
		return songid;
	}

	public void setSongid(String songid) {
		this.songid = songid;
	}

	@Override
	public String toString() {
		return "ReportSong [reportid=" + reportid + ", songid=" + songid + "]";
	}
	
}
